# Generated by Django 3.1.2 on 2021-02-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
