# Generated by Django 3.1.2 on 2021-03-03 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 22, 6, 37, 794))),
                ('eventStartDate', models.DateTimeField()),
                ('eventEndDate', models.DateTimeField()),
                ('eventType', models.CharField(blank=True, max_length=500)),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.catering')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.venue')),
            ],
        ),
        migrations.RenameField(
            model_name='extraservice',
            old_name='cateringID',
            new_name='catering',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 22, 6, 37, 1787))),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=1000)),
                ('feedbackDate', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 22, 6, 37, 2785))),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
