# Generated by Django 3.1.2 on 2020-12-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('openTime', models.DateTimeField()),
                ('closingTime', models.DateTimeField()),
            ],
        ),
    ]
