# Generated by Django 3.1.2 on 2021-03-03 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210303_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='customerID',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 22, 26, 12, 707873)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 22, 26, 12, 708871)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 3, 22, 26, 12, 707873)),
        ),
    ]
