# Generated by Django 3.1.2 on 2020-12-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
