# Generated by Django 3.1.2 on 2021-02-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_venue_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='min_guestCapacity',
        ),
    ]
