# Generated by Django 3.1.2 on 2021-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_venue_min_guestcapacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
