# Generated by Django 3.1.2 on 2021-03-06 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210303_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 6, 23, 11, 54, 930048)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 6, 23, 11, 54, 930048)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 6, 23, 11, 54, 930048)),
        ),
        migrations.RemoveField(
            model_name='venue',
            name='addService',
        ),
        migrations.AddField(
            model_name='venue',
            name='addService',
            field=models.ManyToManyField(to='accounts.extraService'),
        ),
    ]
