# Generated by Django 3.1.2 on 2020-12-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_venue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='closingTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='openTime',
            field=models.TimeField(),
        ),
    ]
