# Generated by Django 3.1.2 on 2021-03-06 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210306_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 6, 23, 25, 10, 829118)),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='catering',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.catering'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 6, 23, 25, 10, 830116)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 6, 23, 25, 10, 830116)),
        ),
    ]
