# Generated by Django 3.1.2 on 2020-12-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201216_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
