# Generated by Django 3.1.2 on 2021-02-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210221_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='min_guestCapacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
