# Generated by Django 3.1.2 on 2021-04-02 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210402_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 2, 19, 51, 26, 965197)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 2, 19, 51, 26, 965197)),
        ),
    ]
