# Generated by Django 3.1.2 on 2020-12-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201216_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='location',
        ),
    ]
