# Generated by Django 3.1.2 on 2021-04-03 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210403_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='catering',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 10, 48, 24, 806175)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 10, 48, 24, 805178)),
        ),
    ]
