# Generated by Django 3.1.2 on 2021-03-13 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210310_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guestNumebr',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 14, 9, 20, 482285)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 14, 9, 20, 484273)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 14, 9, 20, 483280)),
        ),
    ]
