# Generated by Django 3.1.2 on 2021-04-03 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210403_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorrequest',
            old_name='title',
            new_name='venue_name',
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 17, 21, 21, 468849)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 17, 21, 21, 468849)),
        ),
    ]
