# Generated by Django 3.1.2 on 2021-03-13 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210313_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guestNumebr',
        ),
        migrations.AddField(
            model_name='booking',
            name='guestNumeber',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 37, 24, 610574)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 37, 24, 609579)),
        ),
    ]
