# Generated by Django 3.1.2 on 2021-04-03 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210403_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='request_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 17, 24, 4, 439543)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 17, 24, 4, 438546)),
        ),
        migrations.AlterField(
            model_name='vendorrequest',
            name='venue_name',
            field=models.CharField(max_length=100),
        ),
    ]
