# Generated by Django 3.1.2 on 2021-04-03 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210403_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='vendor_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendorrequest'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 17, 40, 19, 962903)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 17, 40, 19, 961906)),
        ),
        migrations.AlterField(
            model_name='vendorrequest',
            name='venue_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
