# Generated by Django 3.1.2 on 2021-03-13 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210313_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guestNumeber',
            new_name='guestNumber',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 37, 41, 197056)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 37, 41, 197056)),
        ),
    ]
