# Generated by Django 3.1.2 on 2021-04-03 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210403_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='vendor_request',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 17, 58, 46, 676697)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 17, 58, 46, 675702)),
        ),
    ]
