# Generated by Django 3.1.2 on 2021-03-13 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210313_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guestNumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 54, 50, 863560)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 54, 50, 862566)),
        ),
    ]
