# Generated by Django 3.1.2 on 2021-04-03 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210403_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 18, 14, 11, 14423)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 18, 14, 11, 13426)),
        ),
    ]
