# Generated by Django 3.1.2 on 2021-03-13 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210313_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='extraService',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 16, 56, 20, 126427)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 16, 56, 20, 126427)),
        ),
    ]
