# Generated by Django 3.1.2 on 2021-03-13 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210313_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extraService',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.extraservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='serviceType',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 19, 16, 18, 716627)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 19, 16, 18, 716627)),
        ),
    ]
