# Generated by Django 3.1.2 on 2021-04-08 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210408_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorrequest',
            old_name='phone_number',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 11, 59, 17, 659209)),
        ),
    ]
