# Generated by Django 3.1.2 on 2021-04-08 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210408_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 12, 9, 5, 84843)),
        ),
    ]
