# Generated by Django 3.1.2 on 2021-04-08 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210408_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraservice',
            name='catering',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 20, 16, 44, 310534)),
        ),
    ]
