# Generated by Django 3.1.2 on 2021-04-08 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210408_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraservice',
            name='catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.catering'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 8, 20, 26, 15, 69365)),
        ),
    ]
