# Generated by Django 3.1.2 on 2021-04-09 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210409_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='eventEndDate',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 9, 19, 54, 51, 889386)),
        ),
    ]
