# Generated by Django 3.1.2 on 2021-04-10 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210410_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservice',
            name='servicePrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 10, 18, 36, 16, 879933)),
        ),
    ]
