# Generated by Django 3.1.2 on 2021-04-10 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210410_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservice',
            name='catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.catering'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 10, 18, 37, 33, 831259)),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='venue',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.venue'),
        ),
    ]
