# Generated by Django 3.2 on 2021-04-16 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_payment_paymentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='address',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='district',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 23, 59, 30, 594057)),
        ),
    ]
