# Generated by Django 3.2 on 2021-04-16 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0039_alter_payment_paymentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='venueName',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='req_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='request_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='venue_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 0, 8, 20, 614248)),
        ),
    ]
