# Generated by Django 3.2 on 2021-04-17 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20210417_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 8, 18, 59, 342894)),
        ),
    ]
