# Generated by Django 3.2 on 2021-04-17 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210417_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='req_from',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 8, 50, 54, 369356)),
        ),
    ]
