# Generated by Django 3.2 on 2021-04-21 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_payment_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 17, 58, 10, 563319)),
        ),
    ]
