# Generated by Django 3.2 on 2021-04-24 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_payment_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 24, 13, 48, 24, 298318)),
        ),
    ]
